name: dStor-node-api CI deploy to STAGENET

# **What it does**: Deploys the API to the mainnet OBE when a release has been approved by two users and released.
# **Why we have it**: Automatic updates to mainnet.
# **Who does it impact**: All mainnet users and work will be affected by this update. The update has been shortened to minimize any downtime.

on:
  push:
    branches: [ stage, stagenet ]
jobs:

  apply_to_Stagenet:
    runs-on: ubuntu-latest
    steps:
    - name: update remote repo
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SHHOST }}
        username: ${{ secrets.SHUSERNAME }}
        password: ${{ secrets.SHPASSWORD }}
        port: ${{ secrets.SHPORT }}
        script_stop: true
        script: |
          cd open-block-explorer
          cp .env  ~/obe.env
          git pull --autostash
          cp ~/obe.env .env
          rm -rf dist/spa/*
          yarn install
          yarn quasar build
